<a href="https://colab.research.google.com/github/Nivoter/HackCV/blob/master/PR01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Задание 1

Объясните результат операции:

In [17]:
print(arr[:5:-2])

[10, 8]


Если задан отрицательный шаг, то index_start и index_end меняются местами, следовательно выполнена следующая запись [index_end:index_start:-2] 

Также, в случае незаданного index_end он равняется индексу конца массива

Поэтому эта команда и вывела элементы с конца до 5 с шагом 2


Задание 2

Получите перевернутый список:

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [19]:
data = list(range(10))
print(data)

# TODO - [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
print(data[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


Задание 3

Получите массив без первого и двух последних элементов:

In [20]:
data = list(range(10))
print(data)

# TODO - [1, 2, 3, 4, 5, 6, 7]
print(data[1:8])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7]



Задание 4

Получите массив без крайних рядов и колонок (по одной с каждой стороны)

In [29]:
data = np.random.randint(low=0, high=10, size=(5, 6))
print(data)
print('/////////')
print(data[1:5,1:5])
# TODO - центральная часть массива размером (4, 5)

[[2 4 8 1 1 3]
 [9 1 0 6 1 6]
 [4 3 4 1 0 1]
 [8 8 1 5 5 5]
 [4 9 3 9 4 5]]
/////////
[[1 0 6 1]
 [3 4 1 0]
 [8 1 5 5]
 [9 3 9 4]]


Задание 5

Произведите перемешивание колонок с помощью функции numpy.random.permutation():

In [51]:

data = np.random.randint(low=0, high=10, size=(3, 6))
print(data)

# TODO - такой же массив, но со случайной перестановкой колонок
print('/////////')

print(data[:,np.random.permutation(6)])

[[0 4 0 3 7 5]
 [3 9 7 3 4 3]
 [2 4 9 9 3 1]]
/////////
[[5 4 7 3 0 0]
 [3 9 4 3 7 3]
 [1 4 3 9 9 2]]



Задание 6

Определите, имеется ли хотя бы одно значение больше пяти и меньше восьми в массиве:

In [61]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

# TODO - определить, имеется ли в массиве хотя бы один элемент, 
#           отвечающий условию больше пяти и меньше восьми

np.any((arr>5)&(arr<8))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


True

Задание

Напишите операцию получения суммы элементов по всем стобцам:

In [63]:

data = np.random.randint(low=0, high=5, size=(3, 6))
print(data)

# TODO - вектор сумм элементов по каждому столбцу
data1 = np.sum(data,axis=0)
print(data1)

[[2 0 1 2 4 2]
 [4 0 3 2 3 1]
 [1 0 2 2 1 3]]
[7 0 6 6 8 6]


In [65]:

x = np.ones((4, 1, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))
print(x)
print(y)
print((x*y).shape)

[[[1.]]

 [[1.]]

 [[1.]]

 [[1.]]]
[[[3 2]
  [1 1]
  [4 3]]

 [[3 2]
  [0 3]
  [3 0]]

 [[4 3]
  [0 4]
  [3 0]]

 [[2 4]
  [2 0]
  [3 3]]]
(4, 3, 2)
